package types

const (
	SettingTypeRewriteSystemMessage                = "REWRITE_SYSTEM_MESSAGE"
	SettingTypePredictIntentSystemMessage          = "PREDICT_INTENT_SYSTEM_MESSAGE"
	SettingTypePredictEntitiesSystemMessage        = "PREDICT_ENTITIES_SYSTEM_MESSAGE"
	SettingTypeAskSystemMessage                    = "ASK_SYSTEM_MESSAGE"
	SettingTypeCheckNeedReplySystemMessage         = "CHECK_NEED_REPLY_SYSTEM_MESSAGE"
	SettingTypeCondenseSystemMessage               = "CONDENSE_SYSTEM_MESSAGE"
	SettingTypeSaveSystemMessage                   = "SAVE_SYSTEM_MESSAGE"
	SettingTypeGenerateSQLSystemMessage            = "GENERATE_SQL_SYSTEM_MESSAGE"
	SettingTypeGenerateStepsSystemMessage          = "GENERATE_STEPS_SYSTEM_MESSAGE"
	SettingTypeCheckNeedGenerateSlideSystemMessage = "CHECK_NEED_GENERATE_SLIDE_SYSTEM_MESSAGE"
	SettingTypeExecuteSystemMessage                = "EXECUTE_SYSTEM_MESSAGE"
	SettingTypeAddSlideToDeckSystemMessage         = "ADD_SLIDE_TO_DECK_SYSTEM_MESSAGE"
	SettingTypeWriteArticleSystemMessage           = "WRITE_ARTICLE_SYSTEM_MESSAGE"
	SettingTypeConsolidateSystemMessage            = "CONSOLIDATE_SYSTEM_MESSAGE"
	SettingTypeGenerateHookSystemMessage           = "GENERATE_HOOK_SYSTEM_MESSAGE"
	SettingTypeGenerateBridgeSystemMessage         = "GENERATE_BRIDGE_SYSTEM_MESSAGE"
	SettingTypeBookAppointmentSystemMessage        = "BOOK_APPOINTMENT_SYSTEM_MESSAGE"
	SettingTypeACTSystemMessage                    = "ACT_SYSTEM_MESSAGE"
	SettingTypeReplySystemMessage                  = "REPLY_SYSTEM_MESSAGE"
	SettingTypeSummarizeSystemMessage              = "SUMMARIZE_SYSTEM_MESSAGE"
	SettingTypeCreateWebsiteSystemMessage          = "CREATE_WEBSITE_SYSTEM_MESSAGE"
	SettingTypeCreateWebsiteCSSSystemMessage       = "CREATE_WEBSITE_CSS_SYSTEM_MESSAGE"
	SettingTypeRAGSystemMessage                    = "RAG_SYSTEM_MESSAGE"
	SettingTypeExtractKnowledgeSystemMessage       = "EXTRACT_KNOWLEDGE_SYSTEM_MESSAGE"
)
