BEGIN;
CREATE SCHEMA "ai_agent";
CREATE TABLE "ai_agent"."profiles" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "business_account_id" integer NOT NULL,
  "name" text NOT NULL,
  "description" text NOT NULL,
  "business_info" jsonb NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "budget_daily" integer NOT NULL,
  "budget_7_days" integer NOT NULL,
  "budget_30_days" integer NOT NULL,
  "handover_message" text NOT NULL,
  "never_say_phrases" text[] NULL,
  "utc_offset_hours" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "profiles_business_account_id_fkey" FOREIGN KEY ("business_account_id") REFERENCES "wa"."business_accounts" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "profiles_business_info_array_check" CHECK (jsonb_typeof(business_info) = 'array'::text)
);
CREATE INDEX "profiles_business_account_id_idx" ON "ai_agent"."profiles" ("business_account_id", "id");
CREATE UNIQUE INDEX "profiles_business_account_id_name_unique" ON "ai_agent"."profiles" ("business_account_id", "name");
COMMENT ON COLUMN "ai_agent"."profiles"."budget_daily" IS 'divide by 1000 for decimal';
COMMENT ON COLUMN "ai_agent"."profiles"."budget_7_days" IS 'divide by 1000 for decimal';
COMMENT ON COLUMN "ai_agent"."profiles"."budget_30_days" IS 'divide by 1000 for decimal';
CREATE TABLE "ai_agent"."faqs" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "profile_id" integer NOT NULL,
  "type" text NOT NULL,
  "question" text NOT NULL,
  "answer" text NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "faqs_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "ai_agent"."profiles" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "faqs_profile_id_idx" ON "ai_agent"."faqs" ("profile_id", "id");
ALTER TABLE "wa"."phone_numbers" ADD COLUMN "agent_profile_id" integer NULL, ADD
CONSTRAINT "phone_numbers_agent_profile_id_fkey" FOREIGN KEY ("agent_profile_id") REFERENCES "ai_agent"."profiles" ("id") ON UPDATE CASCADE ON DELETE SET NULL;
CREATE INDEX "phone_numbers_agent_profile_id_idx" ON "wa"."phone_numbers" ("agent_profile_id");
CREATE TABLE "ai_agent"."skills" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "profile_id" integer NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "skills_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "ai_agent"."profiles" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "skills_profile_id_idx" ON "ai_agent"."skills" ("profile_id", "id");
CREATE TABLE "ai_agent"."websites" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "profile_id" integer NOT NULL,
  "url" text NOT NULL,
  "exclude_patterns" text[] NULL,
  "include_subdomains" boolean NOT NULL,
  "job_id" text NOT NULL,
  "status" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "include_patterns" text[] NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "websites_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "ai_agent"."profiles" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "ai_agent_websites_business_account_id_idx" ON "ai_agent"."websites" ("profile_id");
CREATE TRIGGER faqs_set_last_update
BEFORE UPDATE ON ai_agent.faqs
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER profiles_set_last_update
BEFORE UPDATE ON ai_agent.profiles
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER skills_set_last_update
BEFORE UPDATE ON ai_agent.skills
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER websites_set_last_update
BEFORE UPDATE ON ai_agent.websites
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
COMMIT;
ANALYZE;