BEGIN;
CREATE TABLE "wa"."business_agent_keywords" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "phone_number_id" integer NOT NULL,
  "keyword" text NOT NULL,
  "notification_title" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "business_agent_keywords_phone_number_id_fkey" FOREIGN KEY ("phone_number_id") REFERENCES "wa"."phone_numbers" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "business_agent_keywords_phone_number_id_idx" ON "wa"."business_agent_keywords" ("phone_number_id", "id");
CREATE TRIGGER business_agent_keywords_set_last_update
BEFORE UPDATE ON wa.business_agent_keywords
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
COMMIT;
ANALYZE;