BEGIN;
ALTER TABLE account.users DISABLE TRIGGER USER;
DELETE FROM "account"."users" WHERE "users"."id" = 19;
DELETE FROM "account"."users" WHERE "users"."id" = 20;
DELETE FROM "account"."users" WHERE "users"."id" = 21;
ALTER TABLE account.users ENABLE TRIGGER USER;
ALTER TABLE wa.business_portfolios DISABLE TRIGGER USER;
DELETE FROM "wa"."business_portfolios" WHERE "business_portfolios"."id" = 8;
ALTER TABLE wa.business_portfolios ENABLE TRIGGER USER;
ALTER TABLE wa.business_accounts DISABLE TRIGGER USER;
DELETE FROM "wa"."business_accounts" WHERE "business_accounts"."id" = 11;
ALTER TABLE wa.business_accounts ENABLE TRIGGER USER;
ALTER TABLE wa.phone_numbers DISABLE TRIGGER USER;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 17;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 18;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 19;
ALTER TABLE wa.phone_numbers ENABLE TRIGGER USER;
-- Reset identity sequences to the previous max id after rollback;
-- This ensures clean state after removing data;
SELECT setval(pg_get_serial_sequence('account.users', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.business_portfolios', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.business_accounts', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.phone_numbers', 'id'), 0, false);
COMMIT;