BEGIN;
DROP SCHEMA "ai" CASCADE;
CREATE SCHEMA "ai_worker";
CREATE TABLE "ai_worker"."conversations" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "title" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "conversations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "conversations_user_id_idx" ON "ai_worker"."conversations" ("user_id");
CREATE TABLE "ai_worker"."messages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "conversation_id" integer NOT NULL,
  "parts" text[] NOT NULL,
  "role" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "feature" text NOT NULL,
  "url" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "ai_worker"."conversations" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "messages_role_check" CHECK (role = ANY (ARRAY['USER'::text, 'ASSISTANT'::text]))
);
CREATE INDEX "messages_conversation_id_idx" ON "ai_worker"."messages" ("conversation_id");
CREATE TRIGGER conversations_set_last_update
BEFORE UPDATE ON ai_worker.conversations
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER messages_set_last_update
BEFORE UPDATE ON ai_worker.messages
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
COMMIT;
ANALYZE;