BEGIN;
CREATE TABLE account.sessions (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  token_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  last_used_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at timestamptz NULL,
  entry_date timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_update timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT sessions_token_hash_unique UNIQUE (token_hash),
  CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES account.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX sessions_expires_at_index ON account.sessions (expires_at);
CREATE INDEX sessions_user_id_index ON account.sessions (user_id);
CREATE TRIGGER sessions_set_last_update
BEFORE UPDATE ON account.sessions
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
DROP INDEX account.users_access_token_hash_unique;
ALTER TABLE account.users DROP COLUMN access_token_expiry;
ALTER TABLE account.users DROP COLUMN access_token_hash;
COMMIT;