BEGIN;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
CREATE SCHEMA "account";
CREATE SCHEMA "commerce";
CREATE SCHEMA "customer";
CREATE SCHEMA "site";
CREATE SCHEMA "wa";
CREATE UNLOGGED TABLE "account"."cache" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "key" text NOT NULL,
  "value" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "account_cache_key_unique" UNIQUE ("key")
);
CREATE TABLE "wa"."sample_templates" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "category" text NOT NULL,
  "language" text NOT NULL,
  "parameter_format" text NOT NULL,
  "components" jsonb NOT NULL DEFAULT '[]',
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "wa"."business_portfolios" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "meta_business_portfolio_id" text NOT NULL,
  "name" public.citext NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "access_token_encrypted" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "meta_business_portfolio_id_unique" UNIQUE ("meta_business_portfolio_id")
);
CREATE TABLE "wa"."business_accounts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "waba_id" text NOT NULL,
  "name" public.citext NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "timezone_id" text NOT NULL,
  "business_portfolio_id" integer NOT NULL,
  "currency" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "business_accounts_meta_waba_id_unique" UNIQUE ("waba_id"),
  CONSTRAINT "business_accounts_business_portfolio_id_fkey" FOREIGN KEY ("business_portfolio_id") REFERENCES "wa"."business_portfolios" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE "account"."users" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "password_hash" text NOT NULL,
  "type" text NOT NULL,
  "description" text NOT NULL,
  "status" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "country_code" text NOT NULL,
  "phone_number_encrypted" text NOT NULL,
  "phone_number_hash" text NOT NULL,
  "email_encrypted" text NOT NULL,
  "email_hash" text NOT NULL,
  "encryption_id" uuid NOT NULL,
  "close_reason" text NOT NULL,
  "close_reason_types" text[] NULL,
  "business_account_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_business_account_id_fkey" FOREIGN KEY ("business_account_id") REFERENCES "wa"."business_accounts" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX "users_email_hash_idx" ON "account"."users" ("email_hash");
CREATE INDEX "users_phone_number_hash_idx" ON "account"."users" ("country_code", "phone_number_hash");
CREATE TABLE "customer"."broadcasts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "send_date" timestamptz NOT NULL,
  "wa_template_id" text NOT NULL,
  "user_id" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'PENDING',
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "send_template_payload" jsonb NOT NULL DEFAULT '{}',
  "token" text NOT NULL,
  "attachment_url" text NOT NULL,
  "template_payload" jsonb NOT NULL DEFAULT '{}',
  "recipient_count" integer NOT NULL,
  "error_message" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "customer_campaigns_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE "wa"."phone_numbers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" public.citext NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status" text NOT NULL,
  "business_account_id" integer NOT NULL,
  "meta_phone_number_id" text NOT NULL,
  "registration_pin_encrypted" text NOT NULL,
  "display_phone_number_encrypted" text NOT NULL,
  "wa_id_encrypted" text NOT NULL,
  "wa_id_hash" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "phone_numbers_business_account_id_fkey" FOREIGN KEY ("business_account_id") REFERENCES "wa"."business_accounts" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX "phone_numbers_wa_id_hashed_idx" ON "wa"."phone_numbers" ("wa_id_hash");
CREATE TABLE "customer"."customers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "display_name" text NOT NULL,
  "country_code" text NOT NULL,
  "meta_user_id" text NOT NULL DEFAULT '',
  "tags" text[] NULL,
  "added_at" timestamptz NOT NULL DEFAULT now(),
  "last_updated_at" timestamptz NOT NULL DEFAULT now(),
  "status" text NOT NULL DEFAULT 'ACTIVE',
  "remarks" text NOT NULL,
  "wa_display_name" text NOT NULL,
  "token" text NOT NULL,
  "phone_number_encrypted" text NOT NULL,
  "phone_number_hash" text NOT NULL,
  "wa_id_encrypted" text NOT NULL,
  "wa_id_hash" text NOT NULL,
  "additional_data_encrypted" text NOT NULL,
  "imported_phone_number_encrypted" text NOT NULL,
  "imported_phone_number_hash" text NOT NULL,
  "phone_number_id" integer NOT NULL,
  "from_incoming_message" boolean NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "customers_phone_number_id_fkey" FOREIGN KEY ("phone_number_id") REFERENCES "wa"."phone_numbers" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX "customers_phone_number_id_idx" ON "customer"."customers" ("phone_number_id");
CREATE UNIQUE INDEX "token_1789179939844_index" ON "customer"."customers" ("token");
CREATE TABLE "wa"."messages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "sending" boolean NOT NULL,
  "wa_message_id" text NOT NULL,
  "timestamp" bigint NOT NULL,
  "type" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status" text NOT NULL DEFAULT 'accepted',
  "attachment_url" text NOT NULL,
  "category" text NOT NULL,
  "billable" boolean NOT NULL DEFAULT false,
  "billing_type" text NOT NULL,
  "customer_id" integer NOT NULL,
  "phone_number_id" integer NOT NULL DEFAULT 0,
  "attempts" integer NOT NULL DEFAULT 0,
  "error_message" text NOT NULL,
  "token" text NOT NULL,
  "next_attempt_at" timestamptz NULL,
  "payload_encrypted" text NOT NULL,
  "sender_user_id" integer NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_messages_customer" FOREIGN KEY ("customer_id") REFERENCES "customer"."customers" ("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "messages_phone_number_id_fkey" FOREIGN KEY ("phone_number_id") REFERENCES "wa"."phone_numbers" ("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "messages_user_id_fkey" FOREIGN KEY ("sender_user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE UNIQUE INDEX "idx_wa_messages_wa_message_id_unique" ON "wa"."messages" ("wa_message_id") WHERE ((wa_message_id IS NOT NULL) AND (wa_message_id <> ''::text));
CREATE INDEX "token_1789435127328_index" ON "wa"."messages" ("token");
CREATE TABLE "customer"."broadcast_recipients" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "broadcast_id" integer NOT NULL,
  "customer_id" integer NOT NULL,
  "payload" jsonb NULL,
  "added_at" timestamptz NOT NULL DEFAULT now(),
  "last_updated_at" timestamptz NOT NULL DEFAULT now(),
  "message_id" integer NULL,
  "payload_encrypted" text NOT NULL,
  "encryption_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "campaign_recipient_campaign_id_fkey" FOREIGN KEY ("broadcast_id") REFERENCES "customer"."broadcasts" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "campaign_recipient_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer"."customers" ("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "campaign_recipient_message_id_fk" FOREIGN KEY ("message_id") REFERENCES "wa"."messages" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX "campaign_recipient_customer_idx" ON "customer"."broadcast_recipients" ("customer_id");
CREATE TABLE "commerce"."websites" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "domain_name" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status" text NOT NULL,
  "about" text NOT NULL,
  "description" text NOT NULL,
  "address" text NOT NULL,
  "profile_picture_url" text NOT NULL,
  "email" text NOT NULL,
  "vertical" text NOT NULL,
  "business_account_id" integer NOT NULL,
  "contact_text" text NOT NULL,
  "products_last_synced_at" timestamptz NOT NULL,
  "cover_image_url" text NOT NULL,
  "tagline" text NOT NULL,
  "latitude" double precision NOT NULL,
  "longitude" double precision NOT NULL,
  "copyright_text" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "websites_domain_name_unique" UNIQUE ("domain_name"),
  CONSTRAINT "websites_business_account_id_fkey" FOREIGN KEY ("business_account_id") REFERENCES "wa"."business_accounts" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE "commerce"."catalogs" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "meta_id" text NOT NULL,
  "name" text NOT NULL,
  "vertical" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "website_id" integer NOT NULL,
  "subscribed" boolean NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "catalogs_meta_id_unique" UNIQUE ("meta_id"),
  CONSTRAINT "catalogs_website_id_fkey" FOREIGN KEY ("website_id") REFERENCES "commerce"."websites" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE "site"."feedbacks" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NULL,
  "content" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "site_feedbacks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE TABLE "commerce"."sets" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "catalog_id" integer NOT NULL,
  "meta_id" text NOT NULL,
  "name" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "rank" integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "sets_meta_id_unique" UNIQUE ("meta_id"),
  CONSTRAINT "sets_catalog_id_fkey" FOREIGN KEY ("catalog_id") REFERENCES "commerce"."catalogs" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "sets_catalog_id_idx" ON "commerce"."sets" ("catalog_id");
CREATE TABLE "commerce"."generic_products" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "set_id" integer NOT NULL,
  "meta_id" text NOT NULL,
  "name" text NOT NULL,
  "price" text NOT NULL,
  "availability" text NOT NULL,
  "condition" text NOT NULL,
  "currency" text NOT NULL,
  "description" text NOT NULL,
  "fb_category" text NOT NULL,
  "gender" text NOT NULL,
  "image_url" text NOT NULL,
  "retailer_id" text NOT NULL,
  "url" text NOT NULL,
  "additional_image_urls" text[] NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "sale_price" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "generic_products_set_id_fkey" FOREIGN KEY ("set_id") REFERENCES "commerce"."sets" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "generic_products_set_id_idx" ON "commerce"."generic_products" ("set_id");
COMMENT ON TABLE "commerce"."generic_products" IS 'meta_id can be duplicated becuase there are All Products set';
CREATE TABLE "wa"."message_status" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "wa_message_id" text NOT NULL,
  "status" text NOT NULL,
  "timestamp" bigint NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "message_id" integer NOT NULL,
  "error_message" text NOT NULL,
  "payload_encrypted" text NOT NULL,
  "encryption_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "message_status_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "wa"."messages" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "message_id_1789182934156_index" ON "wa"."message_status" ("message_id");
CREATE INDEX "message_status_events_wa_message_id_timestamp_idx" ON "wa"."message_status" ("wa_message_id", "timestamp" DESC);
CREATE TABLE "account"."notifications" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "title" text NOT NULL,
  "body" text NOT NULL,
  "type" text NOT NULL,
  "url" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "read" boolean NOT NULL,
  "category" text NOT NULL,
  "icon_type" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "notifications_user_id_idx" ON "account"."notifications" ("user_id");
CREATE INDEX "notifications_user_type_idx" ON "account"."notifications" ("user_id", "type");
CREATE TABLE "commerce"."pages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "website_id" integer NOT NULL,
  "slug" text NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "content" text NOT NULL,
  "nav" boolean NOT NULL DEFAULT false,
  "rank" integer NOT NULL DEFAULT 0,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "image_urls" text[] NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "pages_website_id_slug_unique" UNIQUE ("website_id", "slug"),
  CONSTRAINT "pages_website_id_fkey" FOREIGN KEY ("website_id") REFERENCES "commerce"."websites" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "pages_website_id_rank_idx" ON "commerce"."pages" ("website_id");
CREATE TABLE "account"."sessions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "access_token_hashed" text NOT NULL,
  "ip" inet NOT NULL,
  "user_agent" text NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "last_used_at" timestamptz NOT NULL,
  "revoked_at" timestamptz NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "access_token_hashed_unique" UNIQUE ("access_token_hashed"),
  CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "sessions_active_lookup_idx" ON "account"."sessions" ("access_token_hashed", "expires_at") WHERE (revoked_at IS NULL);
CREATE TABLE "account"."settings" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" public.citext NOT NULL,
  "value" text NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE "account"."user_phone_numbers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "phone_number_id" integer NOT NULL,
  "added_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_phone_numbers_user_phone_unique" UNIQUE ("user_id", "phone_number_id"),
  CONSTRAINT "user_phone_numbers_phone_number_id_fkey" FOREIGN KEY ("phone_number_id") REFERENCES "wa"."phone_numbers" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "user_phone_numbers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX "user_phone_numbers_phone_number_id_idx" ON "account"."user_phone_numbers" ("phone_number_id");
CREATE INDEX "user_phone_numbers_user_id_idx" ON "account"."user_phone_numbers" ("user_id");
CREATE OR REPLACE FUNCTION update_last_update_column()
RETURNS TRIGGER AS $$
BEGIN
    -- Only operate on UPDATEs
    IF TG_OP = 'UPDATE' THEN
        -- Only consider when the row data actually changed
        IF (NEW.* IS DISTINCT FROM OLD.*) THEN
            -- If caller did not explicitly set last_updated_at (NULL)
            -- or left it equal to the old value, then set it to now().
            -- If caller set a different last_updated_at, respect that value.
            IF NEW.last_updated_at IS NULL OR NEW.last_updated_at = OLD.last_updated_at THEN
                NEW.last_updated_at = now();
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
;
CREATE TRIGGER cache_set_last_update
BEFORE UPDATE ON account.cache
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER notifications_set_last_update
BEFORE UPDATE ON account.notifications
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER sessions_set_last_update
BEFORE UPDATE ON account.sessions
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER settings_set_last_update
BEFORE UPDATE ON account.settings
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER user_phone_numbers_set_last_update
BEFORE UPDATE ON account.user_phone_numbers
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER users_set_last_update
BEFORE UPDATE ON account.users
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER catalogs_set_last_update
BEFORE UPDATE ON commerce.catalogs
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER generic_products_set_last_update
BEFORE UPDATE ON commerce.generic_products
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER pages_set_last_update
BEFORE UPDATE ON commerce.pages
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER sets_set_last_update
BEFORE UPDATE ON commerce.sets
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER websites_set_last_update
BEFORE UPDATE ON commerce.websites
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER broadcast_recipients_set_last_update
BEFORE UPDATE ON customer.broadcast_recipients
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER broadcasts_set_last_update
BEFORE UPDATE ON customer.broadcasts
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER customers_set_last_update
BEFORE UPDATE ON customer.customers
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER feedbacks_set_last_update
BEFORE UPDATE ON site.feedbacks
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER business_accounts_set_last_update
BEFORE UPDATE ON wa.business_accounts
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER business_portfolios_set_last_update
BEFORE UPDATE ON wa.business_portfolios
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER message_status_set_last_update
BEFORE UPDATE ON wa.message_status
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER messages_set_last_update
BEFORE UPDATE ON wa.messages
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER phone_numbers_set_last_update
BEFORE UPDATE ON wa.phone_numbers
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER sample_templates_set_last_update
BEFORE UPDATE ON wa.sample_templates
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
COMMIT;
ANALYZE;