BEGIN;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
CREATE SCHEMA "account";
CREATE SCHEMA "customer";
CREATE SCHEMA "wa";
CREATE TABLE "wa"."sample_templates" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "category" text NOT NULL,
  "language" text NOT NULL,
  "parameter_format" text NOT NULL,
  "components" jsonb NOT NULL DEFAULT '[]',
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "wa"."business_portfolios" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "meta_business_portfolio_id" text NOT NULL,
  "name" account.citext NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "access_token" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "meta_business_portfolio_id_unique" UNIQUE ("meta_business_portfolio_id")
);
CREATE TABLE "wa"."business_accounts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "waba_id" text NOT NULL,
  "name" account.citext NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "timezone_id" text NOT NULL,
  "business_portfolio_id" integer NOT NULL,
  "currency" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "business_accounts_waba_id_unique" UNIQUE ("waba_id"),
  CONSTRAINT "business_accounts_business_portfolio_id_fkey" FOREIGN KEY ("business_portfolio_id") REFERENCES "wa"."business_portfolios" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE "account"."users" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "password_hash" text NOT NULL,
  "type" text NOT NULL,
  "description" text NOT NULL,
  "status" text NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "phone_number" text NOT NULL,
  "country_code" text NOT NULL,
  "email" text NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "customer"."campaigns" (
  "id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
  "name" text NOT NULL,
  "send_date" timestamptz NOT NULL,
  "wa_template_id" text NOT NULL,
  "user_id" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'PENDING',
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "send_template_payload" jsonb NOT NULL DEFAULT '{}',
  "token" text NOT NULL,
  "attachment_url" text NOT NULL,
  "template_payload" jsonb NOT NULL DEFAULT '{}',
  "recipient_count" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "customer_campaigns_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE "customer"."customers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "display_name" text NOT NULL,
  "country_code" text NOT NULL,
  "phone_number" text NOT NULL,
  "meta_user_id" text NOT NULL DEFAULT '',
  "tags" text[] NULL,
  "entry_date" timestamptz NOT NULL DEFAULT now(),
  "last_update" timestamptz NOT NULL DEFAULT now(),
  "user_id" integer NOT NULL,
  "wa_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'ACTIVE',
  "remarks" text NOT NULL,
  "additional_data" jsonb NULL,
  "imported_phone_number" text NOT NULL,
  "wa_display_name" text NOT NULL,
  "token" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "customers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX "customers_user_id_idx" ON "customer"."customers" ("user_id");
CREATE UNIQUE INDEX "token_1789179939844_index" ON "customer"."customers" ("token");
CREATE TABLE "wa"."phone_numbers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" account.citext NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "registration_pin" text NOT NULL,
  "user_id" integer NOT NULL,
  "wa_id" text NOT NULL,
  "status" text NOT NULL,
  "business_account_id" integer NOT NULL,
  "display_phone_number" text NOT NULL,
  "meta_phone_number_id" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "phone_numbers_business_account_id_fkey" FOREIGN KEY ("business_account_id") REFERENCES "wa"."business_accounts" ("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "phone_numbers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE "wa"."messages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "sending" boolean NOT NULL,
  "wa_message_id" text NOT NULL,
  "timestamp" bigint NOT NULL,
  "type" text NOT NULL,
  "payload" jsonb NOT NULL DEFAULT '{}',
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "status" text NOT NULL DEFAULT 'accepted',
  "attachment_url" text NOT NULL,
  "category" text NOT NULL,
  "billable" boolean NOT NULL DEFAULT false,
  "billing_type" text NOT NULL,
  "campaign_id" integer NULL,
  "customer_id" integer NOT NULL,
  "phone_number_id" integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  CONSTRAINT "messages_meta_id_key" UNIQUE ("wa_message_id"),
  CONSTRAINT "fk_messages_campaign" FOREIGN KEY ("campaign_id") REFERENCES "customer"."campaigns" ("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "fk_messages_customer" FOREIGN KEY ("customer_id") REFERENCES "customer"."customers" ("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "messages_phone_number_id_fkey" FOREIGN KEY ("phone_number_id") REFERENCES "wa"."phone_numbers" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE "customer"."campaign_recipients" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "campaign_id" integer NOT NULL,
  "customer_id" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'PENDING',
  "last_error" text NOT NULL DEFAULT '',
  "attempts" integer NOT NULL DEFAULT 0,
  "next_attempt_at" timestamptz NULL,
  "payload" jsonb NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT now(),
  "last_update" timestamptz NOT NULL DEFAULT now(),
  "message_id" integer NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "campaign_recipient_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "customer"."campaigns" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "campaign_recipient_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customer"."customers" ("id") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "fk_campaign_recipients_message" FOREIGN KEY ("message_id") REFERENCES "wa"."messages" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX "campaign_recipient_customer_idx" ON "customer"."campaign_recipients" ("customer_id");
CREATE INDEX "campaign_recipient_pending_idx" ON "customer"."campaign_recipients" ("campaign_id", "status", "next_attempt_at", "id");
CREATE TABLE "wa"."message_status_events" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "wa_message_id" text NOT NULL,
  "status" text NOT NULL,
  "timestamp" bigint NOT NULL,
  "payload" jsonb NOT NULL DEFAULT '{}',
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "message_id" integer NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "message_status_events_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "wa"."messages" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE INDEX "message_id_1789182934156_index" ON "wa"."message_status_events" ("message_id");
CREATE INDEX "message_status_events_wa_message_id_timestamp_idx" ON "wa"."message_status_events" ("wa_message_id", "timestamp" DESC);
CREATE TABLE "account"."sessions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "access_token_hashed" text NOT NULL,
  "ip" inet NOT NULL,
  "user_agent" text NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "last_used_at" timestamptz NOT NULL,
  "revoked_at" timestamptz NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "access_token_hashed_unique" UNIQUE ("access_token_hashed"),
  CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE "account"."settings" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" account.citext NOT NULL,
  "value" text NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE OR REPLACE FUNCTION update_last_update_column()
RETURNS TRIGGER AS $$
BEGIN
    -- Only operate on UPDATEs
    IF TG_OP = 'UPDATE' THEN
        -- Only consider when the row data actually changed
        IF (NEW.* IS DISTINCT FROM OLD.*) THEN
            -- If caller did not explicitly set last_update (NULL)
            -- or left it equal to the old value, then set it to now().
            -- If caller set a different last_update, respect that value.
            IF NEW.last_update IS NULL OR NEW.last_update = OLD.last_update THEN
                NEW.last_update = now();
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
;
CREATE TRIGGER sessions_set_last_update
BEFORE UPDATE ON account.sessions
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER settings_set_last_update
BEFORE UPDATE ON account.settings
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER users_set_last_update
BEFORE UPDATE ON account.users
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER campaign_recipients_set_last_update
BEFORE UPDATE ON customer.campaign_recipients
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER campaigns_set_last_update
BEFORE UPDATE ON customer.campaigns
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER customers_set_last_update
BEFORE UPDATE ON customer.customers
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER business_accounts_set_last_update
BEFORE UPDATE ON wa.business_accounts
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER business_portfolios_set_last_update
BEFORE UPDATE ON wa.business_portfolios
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER message_status_events_set_last_update
BEFORE UPDATE ON wa.message_status_events
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER messages_set_last_update
BEFORE UPDATE ON wa.messages
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER phone_numbers_set_last_update
BEFORE UPDATE ON wa.phone_numbers
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER sample_templates_set_last_update
BEFORE UPDATE ON wa.sample_templates
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
COMMIT;
ANALYZE;