BEGIN;
DROP SCHEMA "account" CASCADE;
DROP SCHEMA "commerce" CASCADE;
DROP SCHEMA "customer" CASCADE;
DROP SCHEMA "site" CASCADE;
DROP SCHEMA "wa" CASCADE;
DROP TABLE "account"."cache";
DROP TABLE "wa"."sample_templates";
DROP TABLE "account"."users";
DROP INDEX "account"."users_email_hash_idx";
DROP INDEX "account"."users_phone_number_hash_idx";
DROP TABLE "customer"."broadcasts";
DROP TABLE "customer"."customers";
DROP INDEX "customer"."customers_user_id_idx";
DROP INDEX "customer"."customers_user_imported_phone_hash_idx";
DROP INDEX "customer"."customers_user_phone_number_hash_idx";
DROP INDEX "customer"."customers_user_wa_id_hash_idx";
DROP INDEX "customer"."token_1789179939844_index";
DROP TABLE "wa"."business_portfolios";
DROP TABLE "wa"."business_accounts";
DROP TABLE "wa"."phone_numbers";
DROP INDEX "wa"."phone_numbers_wa_id_hashed_idx";
DROP TABLE "wa"."messages";
DROP INDEX "wa"."idx_wa_messages_wa_message_id_unique";
DROP INDEX "wa"."token_1789435127328_index";
DROP TABLE "customer"."broadcast_recipients";
DROP INDEX "customer"."campaign_recipient_customer_idx";
DROP TABLE "commerce"."websites";
DROP TABLE "commerce"."catalogs";
DROP TABLE "site"."feedbacks";
DROP TABLE "commerce"."sets";
DROP INDEX "commerce"."sets_catalog_id_idx";
DROP TABLE "commerce"."generic_products";
DROP INDEX "commerce"."generic_products_set_id_idx";
COMMENT ON TABLE "commerce"."generic_products" IS '';
DROP TABLE "wa"."message_status";
DROP INDEX "wa"."message_id_1789182934156_index";
DROP INDEX "wa"."message_status_events_wa_message_id_timestamp_idx";
DROP TABLE "account"."notifications";
DROP INDEX "account"."notifications_user_id_idx";
DROP INDEX "account"."notifications_user_type_idx";
DROP TABLE "commerce"."pages";
DROP INDEX "commerce"."pages_website_id_rank_idx";
DROP TABLE "account"."sessions";
DROP INDEX "account"."sessions_active_lookup_idx";
DROP TABLE "account"."settings";
DROP TRIGGER cache_set_last_update ON account.cache;
DROP TRIGGER notifications_set_last_update ON account.notifications;
DROP TRIGGER sessions_set_last_update ON account.sessions;
DROP TRIGGER settings_set_last_update ON account.settings;
DROP TRIGGER users_set_last_update ON account.users;
DROP TRIGGER catalogs_set_last_update ON commerce.catalogs;
DROP TRIGGER generic_products_set_last_update ON commerce.generic_products;
DROP TRIGGER pages_set_last_update ON commerce.pages;
DROP TRIGGER sets_set_last_update ON commerce.sets;
DROP TRIGGER websites_set_last_update ON commerce.websites;
DROP TRIGGER broadcast_recipients_set_last_update ON customer.broadcast_recipients;
DROP TRIGGER broadcasts_set_last_update ON customer.broadcasts;
DROP TRIGGER customers_set_last_update ON customer.customers;
DROP TRIGGER feedbacks_set_last_update ON site.feedbacks;
DROP TRIGGER business_accounts_set_last_update ON wa.business_accounts;
DROP TRIGGER business_portfolios_set_last_update ON wa.business_portfolios;
DROP TRIGGER message_status_set_last_update ON wa.message_status;
DROP TRIGGER messages_set_last_update ON wa.messages;
DROP TRIGGER phone_numbers_set_last_update ON wa.phone_numbers;
DROP TRIGGER sample_templates_set_last_update ON wa.sample_templates;
COMMIT;