BEGIN;
DROP SCHEMA "ai_agent" CASCADE;
DROP TABLE "ai_agent"."profiles";
DROP INDEX "ai_agent"."profiles_business_account_id_idx";
DROP INDEX "ai_agent"."profiles_business_account_id_name_unique";
COMMENT ON COLUMN "ai_agent"."profiles"."budget_daily" IS '';
COMMENT ON COLUMN "ai_agent"."profiles"."budget_7_days" IS '';
COMMENT ON COLUMN "ai_agent"."profiles"."budget_30_days" IS '';
DROP TABLE "ai_agent"."faqs";
DROP INDEX "ai_agent"."faqs_profile_id_idx";
ALTER TABLE "wa"."phone_numbers" DROP CONSTRAINT "phone_numbers_agent_profile_id_fkey", DROP COLUMN "agent_profile_id";
DROP INDEX "wa"."phone_numbers_agent_profile_id_idx";
DROP TABLE "ai_agent"."skills";
DROP INDEX "ai_agent"."skills_profile_id_idx";
DROP TABLE "ai_agent"."websites";
DROP INDEX "ai_agent"."ai_agent_websites_business_account_id_idx";
DROP TRIGGER faqs_set_last_update ON ai_agent.faqs;
DROP TRIGGER profiles_set_last_update ON ai_agent.profiles;
DROP TRIGGER skills_set_last_update ON ai_agent.skills;
DROP TRIGGER websites_set_last_update ON ai_agent.websites;
COMMIT;