BEGIN;
DROP SCHEMA "account" CASCADE;
DROP SCHEMA "customer" CASCADE;
DROP SCHEMA "wa" CASCADE;
DROP TABLE "wa"."sample_templates";
DROP TABLE "wa"."business_portfolios";
DROP TABLE "wa"."business_accounts";
DROP TABLE "account"."users";
DROP TABLE "customer"."campaigns";
DROP TABLE "customer"."customers";
DROP INDEX "customer"."customers_user_id_idx";
DROP INDEX "customer"."token_1789179939844_index";
DROP TABLE "wa"."phone_numbers";
DROP TABLE "wa"."messages";
DROP TABLE "customer"."campaign_recipients";
DROP INDEX "customer"."campaign_recipient_customer_idx";
DROP INDEX "customer"."campaign_recipient_pending_idx";
DROP TABLE "wa"."message_status_events";
DROP INDEX "wa"."message_id_1789182934156_index";
DROP INDEX "wa"."message_status_events_wa_message_id_timestamp_idx";
DROP TABLE "account"."sessions";
DROP TABLE "account"."settings";
DROP TRIGGER sessions_set_last_update ON account.sessions;
DROP TRIGGER settings_set_last_update ON account.settings;
DROP TRIGGER users_set_last_update ON account.users;
DROP TRIGGER campaign_recipients_set_last_update ON customer.campaign_recipients;
DROP TRIGGER campaigns_set_last_update ON customer.campaigns;
DROP TRIGGER customers_set_last_update ON customer.customers;
DROP TRIGGER business_accounts_set_last_update ON wa.business_accounts;
DROP TRIGGER business_portfolios_set_last_update ON wa.business_portfolios;
DROP TRIGGER message_status_events_set_last_update ON wa.message_status_events;
DROP TRIGGER messages_set_last_update ON wa.messages;
DROP TRIGGER phone_numbers_set_last_update ON wa.phone_numbers;
DROP TRIGGER sample_templates_set_last_update ON wa.sample_templates;
COMMIT;