BEGIN;
ALTER TABLE account.users DISABLE TRIGGER USER;
DELETE FROM "account"."users" WHERE "users"."id" = 22;
DELETE FROM "account"."users" WHERE "users"."id" = 23;
DELETE FROM "account"."users" WHERE "users"."id" = 24;
DELETE FROM "account"."users" WHERE "users"."id" = 25;
DELETE FROM "account"."users" WHERE "users"."id" = 26;
ALTER TABLE account.users ENABLE TRIGGER USER;
ALTER TABLE account.sessions DISABLE TRIGGER USER;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 54;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 55;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 56;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 57;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 58;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 59;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 60;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 61;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 62;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 63;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 64;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 65;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 66;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 67;
DELETE FROM "account"."sessions" WHERE "sessions"."id" = 68;
ALTER TABLE account.sessions ENABLE TRIGGER USER;
ALTER TABLE wa.business_portfolios DISABLE TRIGGER USER;
DELETE FROM "wa"."business_portfolios" WHERE "business_portfolios"."id" = 9;
ALTER TABLE wa.business_portfolios ENABLE TRIGGER USER;
ALTER TABLE wa.business_accounts DISABLE TRIGGER USER;
DELETE FROM "wa"."business_accounts" WHERE "business_accounts"."id" = 12;
DELETE FROM "wa"."business_accounts" WHERE "business_accounts"."id" = 13;
ALTER TABLE wa.business_accounts ENABLE TRIGGER USER;
ALTER TABLE wa.phone_numbers DISABLE TRIGGER USER;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 20;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 21;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 22;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 23;
DELETE FROM "wa"."phone_numbers" WHERE "phone_numbers"."id" = 24;
ALTER TABLE wa.phone_numbers ENABLE TRIGGER USER;
ALTER TABLE wa.message_status_events DISABLE TRIGGER USER;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 190;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 191;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 192;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 193;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 194;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 195;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 196;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 197;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 198;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 199;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 200;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 201;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 202;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 203;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 204;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 205;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 206;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 207;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 208;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 209;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 210;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 211;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 212;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 213;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 214;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 215;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 216;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 217;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 218;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 219;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 220;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 221;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 222;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 223;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 224;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 225;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 226;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 227;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 228;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 229;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 230;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 232;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 233;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 234;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 235;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 236;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 237;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 238;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 239;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 240;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 241;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 242;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 243;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 244;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 245;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 246;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 247;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 248;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 249;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 250;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 251;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 252;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 253;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 254;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 255;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 256;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 257;
DELETE FROM "wa"."message_status_events" WHERE "message_status_events"."id" = 258;
ALTER TABLE wa.message_status_events ENABLE TRIGGER USER;
ALTER TABLE wa.messages DISABLE TRIGGER USER;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 234;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 235;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 236;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 237;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 238;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 239;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 240;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 241;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 242;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 245;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 246;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 247;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 249;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 250;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 251;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 252;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 253;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 254;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 255;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 256;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 257;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 258;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 259;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 260;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 261;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 262;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 263;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 264;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 265;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 266;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 267;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 268;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 269;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 270;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 271;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 272;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 273;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 274;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 275;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 276;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 277;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 278;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 279;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 280;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 281;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 282;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 283;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 284;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 285;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 286;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 287;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 288;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 289;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 290;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 291;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 292;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 293;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 294;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 295;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 296;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 297;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 298;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 299;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 300;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 301;
DELETE FROM "wa"."messages" WHERE "messages"."id" = 302;
ALTER TABLE wa.messages ENABLE TRIGGER USER;
ALTER TABLE wa.sample_templates DISABLE TRIGGER USER;
DELETE FROM "wa"."sample_templates" WHERE "sample_templates"."id" = 1;
DELETE FROM "wa"."sample_templates" WHERE "sample_templates"."id" = 2;
DELETE FROM "wa"."sample_templates" WHERE "sample_templates"."id" = 3;
DELETE FROM "wa"."sample_templates" WHERE "sample_templates"."id" = 4;
DELETE FROM "wa"."sample_templates" WHERE "sample_templates"."id" = 5;
DELETE FROM "wa"."sample_templates" WHERE "sample_templates"."id" = 6;
ALTER TABLE wa.sample_templates ENABLE TRIGGER USER;
ALTER TABLE customer.customers DISABLE TRIGGER USER;
DELETE FROM "customer"."customers" WHERE "customers"."id" = 3143;
DELETE FROM "customer"."customers" WHERE "customers"."id" = 3144;
DELETE FROM "customer"."customers" WHERE "customers"."id" = 3145;
DELETE FROM "customer"."customers" WHERE "customers"."id" = 3146;
DELETE FROM "customer"."customers" WHERE "customers"."id" = 3147;
ALTER TABLE customer.customers ENABLE TRIGGER USER;
ALTER TABLE customer.campaigns DISABLE TRIGGER USER;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 51;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 52;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 53;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 69;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 70;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 74;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 75;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 76;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 77;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 78;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 80;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 81;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 82;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 83;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 84;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 85;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 86;
DELETE FROM "customer"."campaigns" WHERE "campaigns"."id" = 87;
ALTER TABLE customer.campaigns ENABLE TRIGGER USER;
ALTER TABLE customer.campaign_recipients DISABLE TRIGGER USER;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 146;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 147;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 148;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 164;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 165;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 169;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 170;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 171;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 172;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 173;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 175;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 176;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 177;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 178;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 179;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 180;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 181;
DELETE FROM "customer"."campaign_recipients" WHERE "campaign_recipients"."id" = 182;
ALTER TABLE customer.campaign_recipients ENABLE TRIGGER USER;
-- Reset identity sequences to the previous max id after rollback;
-- This ensures clean state after removing data;
SELECT setval(pg_get_serial_sequence('account.users', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('account.sessions', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.business_portfolios', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.business_accounts', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.phone_numbers', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.message_status_events', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.messages', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('wa.sample_templates', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('customer.customers', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('customer.campaigns', 'id'), 0, false);
SELECT setval(pg_get_serial_sequence('customer.campaign_recipients', 'id'), 0, false);
COMMIT;