CREATE SCHEMA IF NOT EXISTS wa;

CREATE TABLE IF NOT EXISTS wa.campaigns (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              text NOT NULL,
    send_date         timestamptz NOT NULL,
    wa_template_id    text NOT NULL,
    user_id           integer NOT NULL,
    status            text NOT NULL DEFAULT 'PENDING',
    attachment_url    text,
    attachment_type   text,
    localtion_name    text,
    location_address  text,
        location_latitude  double precision,
        location_longitude double precision,
    header_text       text,
    body_text         text,
    footer_text       text,
    entry_date        timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update       timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT campaigns_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES account.users (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS campaigns_user_status_send_date_idx
    ON wa.campaigns (user_id, status, send_date DESC);

CREATE OR REPLACE FUNCTION update_last_update_column()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.* IS DISTINCT FROM OLD.* THEN
        IF NEW.last_update IS NULL OR NEW.last_update = OLD.last_update THEN
            NEW.last_update = CURRENT_TIMESTAMP;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS campaigns_set_last_update ON wa.campaigns;

CREATE TRIGGER campaigns_set_last_update
BEFORE UPDATE ON wa.campaigns
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
