CREATE SCHEMA IF NOT EXISTS wa;

CREATE TABLE IF NOT EXISTS wa.messages (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sending               boolean NOT NULL,
    phone_number          text NOT NULL,
    phone_number_id       text NOT NULL,
    customer_name         text NOT NULL DEFAULT '',
    customer_phone_number text NOT NULL,
    customer_meta_user_id text NOT NULL DEFAULT '',
    meta_id               text NOT NULL,
    timestamp             bigint NOT NULL,
    type                  text NOT NULL,
    payload               jsonb NOT NULL DEFAULT '{}'::jsonb,
    entry_date            timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update           timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT messages_meta_id_key UNIQUE (meta_id)
);

CREATE INDEX IF NOT EXISTS messages_phone_number_id_timestamp_idx
    ON wa.messages (phone_number_id, timestamp DESC);

CREATE INDEX IF NOT EXISTS messages_customer_meta_user_id_timestamp_idx
    ON wa.messages (customer_meta_user_id, timestamp DESC);

DROP TRIGGER IF EXISTS messages_set_last_update ON wa.messages;

CREATE TRIGGER messages_set_last_update
BEFORE UPDATE ON wa.messages
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();