CREATE SCHEMA IF NOT EXISTS wa;

CREATE TABLE IF NOT EXISTS wa.message_status_events (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wa_message_id text NOT NULL,
    status        text NOT NULL,
    timestamp     bigint NOT NULL,
    payload       jsonb NOT NULL DEFAULT '{}'::jsonb,
    entry_date    timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_update   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS message_status_events_wa_message_id_timestamp_idx
    ON wa.message_status_events (wa_message_id, timestamp DESC);

DROP TRIGGER IF EXISTS message_status_events_set_last_update ON wa.message_status_events;

CREATE TRIGGER message_status_events_set_last_update
BEFORE UPDATE ON wa.message_status_events
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();