BEGIN;
CREATE SCHEMA "account";
CREATE SCHEMA "wa";
CREATE TABLE "account"."users" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" text NOT NULL,
  "email" public.citext NOT NULL,
  "password_hash" text NOT NULL,
  "type" text NOT NULL,
  "description" text NOT NULL,
  "status" text NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_email_unique" UNIQUE ("email")
);
CREATE TABLE "wa"."business_accounts" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "meta_business_portfolio_id" text NOT NULL,
  "meta_waba_id" text NOT NULL,
  "name" public.citext NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "business_accounts_meta_waba_id_unique" UNIQUE ("meta_waba_id")
);
CREATE TABLE "wa"."business_portfolios" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "meta_business_portfolio_id" text NOT NULL,
  "name" public.citext NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "meta_business_portfolio_id_unique" UNIQUE ("meta_business_portfolio_id")
);
CREATE TABLE "account"."settings" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" public.citext NOT NULL,
  "value" text NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE "wa"."phone_numbers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "meta_business_portfolio_id" text NOT NULL,
  "meta_waba_id" text NOT NULL,
  "meta_phone_number_id" text NOT NULL,
  "phone_number" text NOT NULL,
  "name" public.citext NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "phone_numbers_meta_phone_number_id_unique" UNIQUE ("meta_phone_number_id")
);
CREATE INDEX "meta_business_portfolio_id_1787634107399_index" ON "wa"."phone_numbers" ("meta_business_portfolio_id");
CREATE TABLE "wa"."user_phone_numbers" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "phone_number_id" integer NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_phone_numbers_user_id_phone_number_id_unique" UNIQUE ("user_id", "phone_number_id"),
  CONSTRAINT "user_phone_numbers_phone_number_id_fkey" FOREIGN KEY ("phone_number_id") REFERENCES "wa"."phone_numbers" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "user_phone_numbers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "account"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TRIGGER settings_set_last_update
BEFORE UPDATE ON account.settings
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER users_set_last_update
BEFORE UPDATE ON account.users
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER business_accounts_set_last_update
BEFORE UPDATE ON wa.business_accounts
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER business_portfolios_set_last_update
BEFORE UPDATE ON wa.business_portfolios
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER phone_numbers_set_last_update
BEFORE UPDATE ON wa.phone_numbers
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
CREATE TRIGGER user_phone_numbers_set_last_update
BEFORE UPDATE ON wa.user_phone_numbers
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
COMMIT;
ANALYZE;