BEGIN;
CREATE TABLE "wa"."history_messages" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "waba_id" text NOT NULL,
  "phone_number_id" text,
  "from" text,
  "message_id" text,
  "message_type" text,
  "text_body" text,
  "message_timestamp" text,
  "raw_payload" jsonb NOT NULL,
  "entry_date" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_update" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE INDEX "history_messages_waba_id_index" ON "wa"."history_messages" ("waba_id");
CREATE INDEX "history_messages_phone_number_id_index" ON "wa"."history_messages" ("phone_number_id");
CREATE INDEX "history_messages_message_id_index" ON "wa"."history_messages" ("message_id");
COMMIT;